//
//
// ⚠️ AUTO-GENERATED — DO NOT EDIT
//
// 

/**
 * Consolidated server environment that merges all service-specific environments
 * 
 * This file is auto-generated by env-map.generate.ts
 */

import { authEnv } from "./auth-env.server";
import { dbEnv } from "./db-env.server";
import { shiplogEnv } from "./shiplog-env.server";

/**
 * Extract public environment variables from all sources
 * 
 * Public env vars are those that start with PUBLIC_
 */
export const getAllPublicEnv = () => {
  const allEnvs = {
    ...authEnv,
    ...dbEnv,
    ...shiplogEnv,
  };
  
  // Filter only PUBLIC_ prefixed variables
  return Object.fromEntries(
    Object.entries(allEnvs).filter(([key]) => key.startsWith("PUBLIC_"))
  );
};

/**
 * Export all server environments for easy access
 */
export {
  authEnv,
  dbEnv,
  shiplogEnv,
};