// This file is generated automatically by scripts/generate-routes.ts
// Do not edit this file directly.
// To regenerate this file, run:
//   yarn generate-routes
//
import { components, hooks, utils } from "~/lib/router/generouted-components";

// all paths get defined here...
export const routePaths = [
  "/",
  "/api/cron/weekly-shiplog",
  "/api/cron/weekly-shiplog/ts",
  "/contact",
  "/login",
  "/oauth2/google/callback",
  "/robots[/]txt",
  "/robots[/]txt/ts",
  "/ships",
  "/ships/:slug",
  "/sitemap[/]xml",
  "/sitemap[/]xml/ts",
] as const;
export type Path = (typeof routePaths)[number];

// all params for any given path get defined here...
export type Params = {
  "/ships/:slug": { slug: string };
};

// Utility type to extract the leaf nodes of Params
type LeafNodes<T> = T[keyof T];

// Merge all leaf nodes into one big object type
type MergeLeafNodes<T> = UnionToIntersection<LeafNodes<T>>;

// Utility type to convert a union type to an intersection type
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Combined type of all the leaf nodes
export type AllParams = MergeLeafNodes<Params>;

export const { Link, NavLink } = components<Path, Params>();
export const { useNavigate, useParams } = hooks<Path, Params>();
export const { redirect, generatePath } = utils<Path, Params>();
